---
- name: borg service
  hosts: all
  become: True

  roles:
  - settings

- name: setup server
  hosts: server
  become: True

  roles:
  - server

- name: setting client
  hosts: client
  become: True

  roles:
  - client

#- name: deploy keys
#  hosts: server
#  become: true

#  roles:
#  - key_input
