---
#Настройки Inet Router
- name: set Inet Router
  hosts: inetRouter
  gather_facts: false
  become: True

  roles:
  - inet_Router
#Настройки Routers
#Включение функции пересылки транзитных пакетов через интерфесы роутеров
- name: set Routers
  hosts: routers
  gather_facts: false
  become: True

  roles:
  - routers
#Настройки всех роутеров и серверов с ОС  centos, кроме inetRouter
#Добавление настройки DEFROUTE=no в конфиг интерфейса eth0 (отключение машрута по умолчанию)
#Назначаются ip ШЛЮЗА для всех роутеров и серверов с CENTOS
- name: set defroute
  hosts: centos:!inetRouter
  gather_facts: false
  become: True

  roles:
  - defrouter_centos
#Установка машрутов
- name: set routers
  hosts: all
  gather_facts: false
  become: True

  roles:
  - servers

#Установка пакета tracerouter на все хосты
- name: tracerouter
  hosts: all
  gather_facts: false
  become: True

  roles:
  - tracerouter
