---
- name: tracerouter
  hosts: all
  gather_facts: false
  become: True

  roles:
  - tracerouter


- name: set Inet Router
  hosts: inetRouter
  gather_facts: false
  become: True

  roles:
  - inet_Router

- name: set Routers
  hosts: routers
  gather_facts: false
  become: True

  roles:
  - routers

- name: set defroute
  hosts: centos:!inetRouter
  gather_facts: false
  become: True

  roles:
  - defrouter_centos

- name: set routers
  hosts: all
  gather_facts: false
  become: True

  roles:
  - servers
