---
#Установка пакета traceroute на сервера с ubuntu
- name: Install traceroute
  apt:
    name:
    - traceroute
    state: present
    update_cache: true
  become: true
  when: inventory_hostname in groups['ubuntu']
#Установка пакета traceroute на сервера с centos
- name: Install traceroute centos
  yum:
    name:
    - traceroute
    state: present
    update_cache: true
  become: true
  when: inventory_hostname in groups['centos']
