---
#module handlers
- name: set_firewalld
  service:
    name: firewalld
    state: stopped
    enabled: off

- name: iptables_service
  service:
    name: iptables
    state: restarted
    enabled: yes
