---
#- name: install python3
- name: install crypto
  shell: |
    yum install -y python3 python3-devel python3-pip
    yum install -y gcc libffi-devel python-devel openssl-devel
    python3 -m pip install pip --upgrade
    python3 -m pip install cryptography
    sudo systemctl enable sshd
  become: true


- name: generate_key
  community.crypto.openssh_keypair:
    backend: opensshbin
    path: /home/vagrant/.ssh/id_rsa
  register: ssh_key


#- name: Get ssh keys
  #slurp:
  #  src: /home/vagrant/.ssh/id-rsa.pub
  #register: ssh_keys
  #tags:
#    - ssh

- name: deploy_keys
  delegate_to: server
  ansible.posix.authorized_key:
    key: "{{ssh_key.public_key}}"
    comment: "{{ansible_hostname}}"
    user: borg
  tags:
    - ssh
