---
- name: init borg repo
  shell: |
    chmod 700 ~/.ssh
    sudo chmod 644 ~/.ssh/id_rsa
    chmod 644 ~/.ssh/id_rsa.pub
    export BORG_PASSPHRASE='Otus1234'
    borg init --encryption=repokey borg@192.168.56.166:/var/backup/first
  become: yes
  become_user: borg
  become_method: enable
