---
#include tasks
- name: copy_key
  include_tasks: copy.yml

- name: setting ssh_config
  include_tasks: set_ssh_config.yml

- name: init borg repo
  include_tasks: init_borg.yml

- name: setting auto backup
  include_tasks: auto_backup.yml
