---
#include tasks
#- name: create authorizade_key
#  file:
#    path: /home/borg/.ssh/authorized_key
#    state: touch
#    mode: '600'
#    owner: borg
#    group: borg

- name: setting ssh config
  copy:
    src: 'files/server/{{ item.src }}'
    dest: '{{ item.dest }}'
  loop:
    - { src: hosts, dest: /etc/ }


- name: Create a ext4 filesystem on /dev/sdb1
  community.general.filesystem:
    fstype: ext4
    dev: /dev/sdb

- name: Mount sdb1
  ansible.posix.mount:
    path: /var/backup
    src: /dev/sdb
    fstype: ext4
    opts: rw,auto
    state: present

- name: create borg folder
  file:
    path: /var/backup/first
    state: directory
    mode: '777'
    owner: borg
    group: borg
