---
#Включение функции пересылки транзитных пакетов через интерфесы роутеров  
- name: set up forward packages across routers
  sysctl:
    name: net.ipv4.conf.all.forwarding
    value: '1'
    state: present
