#copy configuration
- name: setting web
  copy:
    src: 'files/sys/{{ item.src }}'
    dest: '{{ item.dest }}'
  loop:
    - { src: nginx.conf, dest: /etc/nginx/ }
    - { src: audit.rules, dest: /etc/audit/rules.d/ }
    - { src: au-remote.conf, dest: /etc/audisp/plugins.d/ }
    - { src: audisp-remote.conf, dest: /etc/audisp/ }
    - { src: auditd.conf, dest: /etc/audit/ }
  notify:
    - restart auditd
