---
#include tasks
- name: ntp
  ansible.builtin.include_tasks:
    file: ntp.yml

- name: install_repo
  ansible.builtin.include_tasks:
    file: install_repo.yml

- name: install_borg
  ansible.builtin.include_tasks:
    file: install_borg.yml

- name: user borg
  ansible.builtin.include_tasks:
    file: set_user.yml

- name: create ssh
  ansible.builtin.include_tasks:
    file: directory_ssh.yml

#- name: create_keys
#  ansible.builtin.include_tasks: "create_keys.yml"
