- name: ntp service
  hosts: all
  become: True
  
  roles:
  - ntp

- name: setup web
  hosts: web
  become: True

  roles:
  - nginx
  - web
  
- name: setup log
  hosts: log
  become: True
  
  roles:
  - log