---
- name: copy ALL files from /mnt to /iso
  copy:
    src: /mnt/
    dest: /iso
    remote_src: yes
    directory_mode: yes
  copy:
    src: files/ks.cfg
    dest: /iso/ks.cfg
    owner: root
    group: root
    mode: 0755
