---
#module handlers
- name: restart auditd
  service:
    name: auditd
    state: restarted
    use: service
    enabled: yes

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restart
    enabled: yes
