---
#Создаём каталог /var/lib/tftpboot/pxelinux.cfg
- name: Create TFTP directory
  file:
    path: /var/lib/tftpboot/pxelinux.cfg
    state: directory
    mode: '0755'

#Копируем файл-меню на сервер
- name: set up pxelinux
  template:
    src: files/default
    dest: /var/lib/tftpboot/pxelinux.cfg/default
    owner: root
    group: root
    mode: 0644

#Извлекаем файлы из RPM-пакета
- name: extract packages syslinux
  shell: rpm2cpio /iso/BaseOS/Packages/syslinux-tftpboot-6.04-5.el8.noarch.rpm | cpio -dimv

#Копируем файлы в каталог /var/lib/tftpboot/
- name: copy files to TFTP share
  copy:
    src: /home/vagrant/tftpboot/{{ item }}
    dest: /var/lib/tftpboot/{{ item }}
    mode: '0644'
    remote_src: true
  with_items:
    - pxelinux.0
    - ldlinux.c32
    - libmenu.c32
    - libutil.c32
    - menu.c32
    - vesamenu.c32

#Копируем файлы в каталог /var/lib/tftpboot/
- name: copy initrd and vmlinuz files to TFTP share
  copy:
    src: /iso/images/pxeboot/{{ item }}
    dest: /var/lib/tftpboot/{{ item }}
    mode: '0755'
    remote_src: true
  with_items:
    - initrd.img
    - vmlinuz
#Перезапускаем TFTP-сервер и добавляем его в автозагрузку
  notify:
    - restart tftp-server
