---
#Назначение машрутов
- name: set up route on inetRouter
  template:
    src: files/inetRouter_eth1.j2
    dest: /etc/sysconfig/network-scripts/route-eth1
    owner: root
    group: root
    mode: 0644
  delegate_to: inetRouter

- name: set up route on office2Server
  template:
    src: files/office2Server.j2
    dest: /etc/sysconfig/network-scripts/route-eth1
    owner: root
    group: root
    mode: 0644
  delegate_to: office2Server

- name: set up route on centralRouter
  template:
    src: 'files/{{ item.src }}'
    dest: '/etc/sysconfig/network-scripts/{{ item.dest }}'
    owner: root
    group: root
    mode: 0644
  delegate_to: centralRouter
  loop:
    - { src: centralRouter_eth5.j2, dest: route-eth5 }
    - { src: centralRouter_eth6.j2, dest: route-eth6 }


- name: set up route on centralServer
  template:
    src: files/centralServer.j2
    dest: /etc/sysconfig/network-scripts/route-eth1
    owner: root
    group: root
    mode: 0644
  delegate_to: centralServer


- name: set up route on office2Router
  template:
    src: files/office2Router.j2
    dest: /etc/sysconfig/network-scripts/route-eth1
    owner: root
    group: root
    mode: 0644
  delegate_to: office2Router

- name: set up route on office1Server
  template:
    src: files/office1Server.j2
    dest: /etc/netplan/50-vagrant.yaml
    owner: root
    group: root
    mode: 0644
  delegate_to: office1Server

- name: set up route on office1Router
  template:
    src: files/office1Router.j2
    dest: /etc/netplan/50-vagrant.yaml
    owner: root
    group: root
    mode: 0644
  delegate_to: office1Router
#Применение настроек для систем с ubuntu
- name: apply_ubuntu
  command: sudo netplan apply
  ignore_errors: true
  become: yes
  when: inventory_hostname in groups['ubuntu']
#Перезагрузка  network для систем с ubuntu
- name: restart network
  command: sudo reboot #systemctl restart network
  become: yes
  when: inventory_hostname in groups['centos']
