# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "work_prometheus"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.network :forwarded_port, guest: 8080, host: 8080, host_ip: "127.0.0.1"
  config.vm.network :forwarded_port, guest: 9090, host: 9090, host_ip: "127.0.0.1"
  config.vm.network :forwarded_port, guest: 9100, host: 9100, host_ip: "127.0.0.1"
  config.vm.network :forwarded_port, guest: 3000, host: 3000, host_ip: "127.0.0.1"
  #config.vm.network "forwarded_port", quest: 8080, host: 8383, auto_correct: true
   
 
end
