# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"


  config.vm.provider "virtualbox" do |v|
    v.memory = 256
    v.cpus = 1
  end

  config.vm.define "RPM" do |rpm|
    rpm.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "net1"
    rpm.vm.hostname = "rpm"
   rpm.vm.provision "shell", path: "script.sh"
  end

  

end
